/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 man2.glb --transform --simplify 
Files: man2.glb [6.26MB] > D:\YASH\web_development_2Dec\NEXT. js\portfolio_2025\public\man2-transformed.glb [867.1KB] (86%)
Author: manoeldarochadeoliveira (https://sketchfab.com/manoeldarochadeoliveira)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/business-man-low-polygon-game-character-b6f6740f883b4749abac47af0045a9dd
Title: Business Man - Low Polygon game character
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/man2-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.business_suit_man} skeleton={nodes.Object_79.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.962} />
        <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.business_suit_man} skeleton={nodes.Object_81.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.962} />
        <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.business_suit_man} skeleton={nodes.Object_83.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.962} />
      </group>
    </group>
  )
}

useGLTF.preload('/man2-transformed.glb')
